Challenge:
  LibroQueLeo:
      experiment: 'LGBM con los modelos de svd y knn como features'
      randomState: 42
      Path:
        input: 'data/02_intermediate/'
        models: 'data/06_models/'
        submissions: 'data/07_model_output/'
      Files:
        train: 'opiniones_train_modelos.csv'
        test: 'opiniones_test_modelos.csv'
        model: 'lgbm_modelos'
        submission: 'lgbm_modelos.csv'
      Predictor:
        # method: [predict_knn, predict_svd, predict_lightgbm, ensamble]
        method: 'predict_lightgbm'
      Ensamble:
        Weights:
          svd: 0.35
          knn: 0.45
          lgbm: 0.20
        Models:
          svd: svd
          knn: knn
          lgbm: lgbm_modelos
